# Generated by Django 5.2.16 on 2026-07-17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iccu", "0010_complex_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["complex__order", "order"],
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
    ]
